/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clustering.ARFF;
import clustering.CSV;
import clustering.Clasificador;
//import clustering.unirInformesGenerados;
import clustering.ConverterCSV;
import java.io.File;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nes Ch
 */
public class EMClusterWeka extends javax.swing.JFrame {

    File archivoSel;
    String band;
    String path;

    /**
     * Creates new form EMClusterWeka
     */
    public EMClusterWeka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gTipoArchivo = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        txtPath = new javax.swing.JTextField();
        btnClusterizar = new javax.swing.JButton();
        btnCSV = new javax.swing.JButton();
        btnARFF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxSeed = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPath.setEditable(false);

        btnClusterizar.setText("Clusterizar");
        btnClusterizar.setEnabled(false);
        btnClusterizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClusterizarActionPerformed(evt);
            }
        });

        btnCSV.setText("Cargar CSV");
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        btnARFF.setText("Cargar ARFF");
        btnARFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnARFFActionPerformed(evt);
            }
        });

        jLabel2.setText("Cargue el archivo fuente");

        jLabel1.setText("Escoja la semilla");

        cbxSeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "50", "100", "250", "500", "750", "1000" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPath)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxSeed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnClusterizar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCSV)
                .addGap(18, 18, 18)
                .addComponent(btnARFF)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCSV)
                    .addComponent(btnARFF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClusterizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClusterizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClusterizarActionPerformed
        // TODO add your handling code here:
        int seed = 0;
        seed = Integer.parseInt(cbxSeed.getSelectedItem().toString());
        if (band == "CSV") {
            String newpath = "";
            ConverterCSV convertir = new ConverterCSV();
            newpath = convertir.Convert(path);
            CSV csv = new CSV();
            try {
                csv.Clustering(newpath, seed);
                Clasificador cl = new Clasificador();
                cl.ClasificadorCluster();
               // unirInformesGenerados unirInformesGenerados = new unirInformesGenerados();
               // unirInformesGenerados.unirInforme();
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
            }
        } else {
            ARFF arff = new ARFF();
            try {
                arff.Clustering(path, seed);
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
            }
        }
    }//GEN-LAST:event_btnClusterizarActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        // TODO add your handling code here:
        JFileChooser abrir = new JFileChooser();
        abrir.setAcceptAllFileFilterUsed(false);

        btnClusterizar.setEnabled(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV", "csv");
        abrir.addChoosableFileFilter(filter);

        if (abrir.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            archivoSel = abrir.getSelectedFile();
            path = archivoSel.getPath();
            txtPath.setText(path);
            band = "CSV";
            btnClusterizar.setEnabled(true);
        }

    }//GEN-LAST:event_btnCSVActionPerformed

    private void btnARFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnARFFActionPerformed
        // TODO add your handling code here:
        JFileChooser abrir = new JFileChooser();
        abrir.setAcceptAllFileFilterUsed(false);

        btnClusterizar.setEnabled(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("ARFF", "arff");
        abrir.addChoosableFileFilter(filter);

        if (abrir.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            archivoSel = abrir.getSelectedFile();
            path = archivoSel.getPath();
            txtPath.setText(path);
            band = "ARFF";
            btnClusterizar.setEnabled(true);
        }
    }//GEN-LAST:event_btnARFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMClusterWeka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMClusterWeka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMClusterWeka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMClusterWeka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMClusterWeka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnARFF;
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnClusterizar;
    private javax.swing.JComboBox<String> cbxSeed;
    private javax.swing.ButtonGroup gTipoArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
